# Generated by Django 2.2.3 on 2019-07-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190728_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='blog.Article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
