# Generated by Django 2.2.3 on 2019-07-31 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190731_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 2, 11, 31, 795004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 2, 11, 31, 795855, tzinfo=utc)),
        ),
    ]
