# Generated by Django 2.2.3 on 2019-08-01 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190731_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 19, 20, 59, 685171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 19, 20, 59, 686111, tzinfo=utc)),
        ),
    ]
