# Generated by Django 2.2.3 on 2019-08-01 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190801_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 19, 21, 58, 378787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 19, 21, 58, 379770, tzinfo=utc)),
        ),
    ]
