# Generated by Django 2.2.3 on 2019-08-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
